### Get Balance
GET http://localhost:3000/balance/0xaBaB20e0511594971787295FAfaf5356E88830B1
Content-Type: application/json

### Add Tokens
POST http://localhost:3000/addTokens
Content-Type: application/json

{
  "address": "0xaBaB20e0511594971787295FAfaf5356E88830B1",
  "amount": "100"
}

### Update Balance
POST http://localhost:3000/updateBalance
Content-Type: application/json

{
  "address": "0xaBaB20e0511594971787295FAfaf5356E88830B1",
  "amount": "200"
}

### Increment Record
POST http://localhost:3000/incrementRecord
Content-Type: application/json

{
  "userID": "0xaBaB20e0511594971787295FAfaf5356E88830B1",
  "month": 8,
  "year": 2024,
  "day": 10,
  "movieId": "300",
  "timeWatched": 120,
  "amountEarned": 5
}

### Add Transaction
POST http://localhost:3000/addTransaction
Content-Type: application/json

{
  "userID": "0xaBaB20e0511594971787295FAfaf5356E88830B1",
  "month": 9,
  "year": 2024,
  "day": 20,
  "txnId": "txn123",
  "walletAddress": "0xaBaB20e0511594971787295FAfaf5356E88830B1",
  "amount": "50",
  "type_": "user"
}


### Increment Record and Add Transaction
POST http://localhost:3000/recordAndAddTransaction
X_API_KEY: 1jj1k31nfkldcmk13n14nvkldn1vfcj1026104
Content-Type: application/json

{
  "userID": "0xaBaB20e0511594971787295FAfaf5356E88830B1",
  "month": 8,
  "year": 2024,
  "day": 10,
  "movieId": "300",
  "timeWatched": 120,
  "amountEarned": 5,
  "txnId": "txn456",
  "walletAddress": "0xaBaB20e0511594971787295FAfaf5356E88830B1",
  "amount": 50,
  "type_": "user"
}

### Batch Increment Records
POST http://localhost:3000/batchIncrementRecords
Content-Type: application/json

{
  "data": [
    {
      "userID": "0xaBaB20e0511594971787295FAfaf5356E88830B1",
      "month": 12,
      "year": 2024,
      "day": 21,
      "movieId": "movie123",
      "timeWatched": 30,
      "amountEarned": 500,
      "txnId": "txn789",
      "walletAddress": "0xaBaB20e0511594971787295FAfaf5356E88830B1",
      "amount": 150,
      "type_": "contentOwner"
    },
    {
      "userID": "0xaBaB20e0511594971787295FAfaf5356E88830B1",
      "month": 11,
      "year": 2024,
      "day": 19,
      "movieId": "movie124",
      "timeWatched": 60,
      "amountEarned": 873,
      "txnId": "txn790",
      "walletAddress": "0xaBaB20e0511594971787295FAfaf5356E88830B1",
      "amount": 200,
      "type_": "user"
    }
  ]
}


### Emit Total Earned By All Users
POST http://localhost:3000/emitTotalEarnedByAllUsers
Content-Type: application/json

{
  "month": 6,
  "year": 2024
}

### Emit Top Earners
POST http://localhost:3000/emitTopEarners
Content-Type: application/json

{
  "month": 6,
  "year": 2024
}

### Get Consolidated By Movie
GET http://localhost:3000/getConsolidatedByMovie?userID=0xaBaB20e0511594971787295FAfaf5356E88830B1&month=7&year=2024&day=20&movieId=movie124
Content-Type: application/json

### Get Consolidated By Month
GET http://localhost:3000/getConsolidatedByMonth?userID=0xaBaB20e0511594971787295FAfaf5356E88830B1&month=7&year=2024
Content-Type: application/json

### Get Consolidated By Year
GET http://localhost:3000/getConsolidatedByYear?userID=0xaBaB20e0511594971787295FAfaf5356E88830B1&year=2024
Content-Type: application/json

### Get Transactions By Month
GET http://localhost:3000/getTransactionsByMonth?userID=0xaBaB20e0511594971787295FAfaf5356E88830B1&month=7&year=2024
Content-Type: application/json

### Get Transactions By Year
GET http://localhost:3000/getTransactionsByYear?userID=0xaBaB20e0511594971787295FAfaf5356E88830B1&year=2024
Content-Type: application/json

### Get Daily Transactions
GET http://localhost:3000/getDailyTransactions?userID=0xaBaB20e0511594971787295FAfaf5356E88830B1&month=7&year=2024&day=20
Content-Type: application/json

### Get User Summary
GET http://localhost:3000/getUserSummary?userID=0xaBaB20e0511594971787295FAfaf5356E88830B1&month=8&year=2024
Content-Type: application/json

### Get Total Transactions By User
GET http://localhost:3000/getTotalTransactionsByUser?userID=0xaBaB20e0511594971787295FAfaf5356E88830B1&month=7&year=2024
Content-Type: application/json

### Get User Details
GET http://localhost:3000/getUserDetails?userID=0xaBaB20e0511594971787295FAfaf5356E88830B1&topYear=2024
Content-Type: application/json

### Get Monthly Yearly Report
GET http://localhost:3000/getMonthlyYearlyReport?month=4&year=2024
Content-Type: application/json

### Add Admin
POST http://localhost:3000/addAdmin
Content-Type: application/json

{
  "newAdmin": "0xaBaB20e0511594971787295FAfaf5356E88830B1"
}

### Remove Admin
POST http://localhost:3000/removeAdmin
Content-Type: application/json

{
  "adminToRemove": "0xaBaB20e0511594971787295FAfaf5356E88830B1"
}

### Set Token Admin
POST http://localhost:3000/setTokenAdmin
Content-Type: application/json

{
  "newTokenAdmin": "0xaBaB20e0511594971787295FAfaf5356E88830B1"
}

### Pause
POST http://localhost:3000/pause
Content-Type: application/json

{}

### Unpause
POST http://localhost:3000/unpause
Content-Type: application/json

{}